name: build WASM

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown

      - name: build
        run: |
          ./bin/build

      - uses: actions/upload-artifact@v4
        with:
          name: rs-boids
          path: target/web
